### ISSUE TITLE
Performance loss trough unecessary db access

### ISSUE THREAD

**Issue by maxdos64** [Open-IoT-Service-Platform/oisp-frontend#122]
https://github.com/Open-IoT-Service-Platform/oisp-frontend/blob/37eeed99b2fdd4fcfeb43d6d5987aa5e03542884/public-interface/iot-entities/postgresql/devices.js#L352

There is no sane reason why we could not combine the two request
- One for the device.id using criterias
- One for the device properties using device.id 
into one single database request

**Comment by oguzcankirmemis** [comment]
If we used the raw query, this was possible. After #154, we replaced the construction there with proper sequelize construction. The main problem is that the second query includes all the other information device has(components, tags, etc...), while the first query does the filtering. If you want to do them all in one query, then you have to join these sub tables at the filtering, which is impossible for sequelize right now, because it does not allow group by statements in the current version. We can check this again in the future after sequelize supports it.
