### ISSUE TITLE
Problems around device update request lead to frontend crash / partial updates does not work

### ISSUE THREAD

**Issue by wagmarcel** [Open-IoT-Service-Platform/oisp-frontend#253]

**Comment by MericFeyz** [comment]
Steps to reproduce the behavior: 
 
```import oisp
client = oisp.Client("http://localhost:4001/v1/api")
client.auth("user1@example.com", "password")
account = client.create_account("test")
client.auth("user1@example.com", "password")
device = account.create_device("device_id", "device_name")
attr = {"OS": "linux", "color": "blue"}
device.set_properties(attributes=attr)
device.update()
attr["color"] = "red"
device.set_properties(attributes=attr)
device.update()
```

Expected: Success
What happens: "ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"

Tested on the latest and v2.1.0-beta.1 builds

**Comment by oguzcankirmemis** [comment]
The crash does not occur on the 'update' call, rather in the 'set_properties' call. The error is also consistent, i.e. the behavior is deterministic. The reason of the error is a bug in the frontend that does not allow partial update of device (only updating attributes or tags) without any update on the metadata of the device itself. 

Apparently, the update call of sequelize does not return the updated value (in this case device), if there is nothing to update (even if it matches). The solution is to make an explicit find call to check if the device exists and raise an error if it does not. This is necessary because update calls generally do not raise an error if the query does not match any value. We also can't depend on the number of affected columns because as stated before: it might be the case that only the attributes table is updated, while the devices table has no updates.

I have linked the PR that solves this bug, I will also rename the issue for more convenience.
